*** Settings ***
Library    OperatingSystem

*** Test Cases ***

Quickly test the Solidty Smart Contract deployed to the Ethereum local fork using Foundry's Cast tool.
    Get Smart Contract Address
    Run Foundry Cast Call Command And Check Results    balanceOf(address)(uint256)
    Run Foundry Cast Call Command And Check Results    name()(string)
    Repeat Keyword    2 times    Run Foundry Cast Send To Mint Specific Token Amounts    100    10

*** Keywords ***

Get Smart Contract Address
     ${TARGET_ADDRESS}    Get File    ${EXECDIR}/anvil-smartcontract-address.env
     Set Suite Variable    ${TARGET_ADDRESS}
     Log To Console     ...
     Log To Console     ...
     Log To Console     ...
     Log To Console     ${TARGET_ADDRESS}
     Log To Console     ...
     Log To Console     ...
     Log To Console     ...

Run Foundry Cast Send To Mint Specific Token Amounts
    [Arguments]    ${MINT_TOKEN_AMOUNT}    ${TIME_DELAY}
    ${FOUNDRY_CAST_OUTPUT}    Run    cast send "${TARGET_ADDRESS}" "mint(address, uint256)" "%{ANVIL_DEFAULT_ACCOUNT_NUMBER}" ${MINT_TOKEN_AMOUNT} --private-key "%{ANVIL_WALLET_PRIVATE_KEY}"
    Log    ${FOUNDRY_CAST_OUTPUT}
    Log To Console    ...
    Log To Console    ...
    Log To Console    ...
    Log To Console    ${FOUNDRY_CAST_OUTPUT}
    Log To Console    ...
    Log To Console    ...
    Log To Console    ...
    Should Not Be Empty    ${FOUNDRY_CAST_OUTPUT}
    Should Not Contain Any    ${FOUNDRY_CAST_OUTPUT}    Error    error
    #Should Contain    ${FOUNDRY_CAST_OUTPUT}    ${FOUNDRY_CAST_CHECK}
    Sleep    ${TIME_DELAY} seconds

Run Foundry Cast Call Command And Check Results
    [Arguments]    ${SMART_CONTRACT_FUNCTION}    #${FOUNDRY_CAST_CHECK}
    ${FOUNDRY_CAST_OUTPUT}    Run    cast call "${TARGET_ADDRESS}" "${SMART_CONTRACT_FUNCTION}" "%{ANVIL_DEFAULT_ACCOUNT_NUMBER}"
    Log    ${FOUNDRY_CAST_OUTPUT}
    Log To Console    ...
    Log To Console    ...
    Log To Console    ...
    Log To Console    ${FOUNDRY_CAST_OUTPUT}
    Log To Console    ...
    Log To Console    ...
    Log To Console    ...
    Should Not Be Empty    ${FOUNDRY_CAST_OUTPUT}
    Should Not Contain Any    ${FOUNDRY_CAST_OUTPUT}    Error    error
    #Should Contain    ${FOUNDRY_CAST_OUTPUT}    ${FOUNDRY_CAST_CHECK}


