*** Settings ***
Library    Remote    http://localhost:${REMOTE_LIBRARY_PORT}

*** Variables ***
${REMOTE_LIBRARY_PORT}    8270

*** Test Cases ***

TRUFFLE WEB3.JS TEST 1 : Get all of the accounts of the local Truffle Develop instance and check the result.
    ${RESULT}=    Get All Available Accounts
    Log To Console    ${RESULT}
    Should Not Be Empty    ${RESULT}

TRUFFLE WEB3.JS TEST 2 : Get the deployed contract from the local Truffle Develop instance and check the result.
    ${RESULT}=    Get Contract    %{CONTRACT_ADDRESS}
    Should Not Be Empty    ${RESULT}

TRUFFLE WEB3.JS TEST 3 : Get the name of the ERC20 token from the local Truffle Develop instance and check the result.
    ${RESULT}=    Get Name    %{CONTRACT_ADDRESS}
    Check Smart Contract Results And Log Them    ${RESULT}    name

TRUFFLE WEB3.JS TEST 4 : Get the symbol of the ERC20 token from the local Truffle Develop instance and check the result.
    ${RESULT}=    Get Symbol    %{CONTRACT_ADDRESS}
    Check Smart Contract Results And Log Them    ${RESULT}    symbol

TRUFFLE WEB3.JS TEST 5 : Get the decimals of the ERC20 token from the local Truffle Develop instance and check the result.
    ${RESULT}=    Get Default Decimals    %{CONTRACT_ADDRESS}
    Check Smart Contract Results And Log Them    ${RESULT}    decimals

TRUFFLE WEB3.JS TEST 6 : Get the total supply of the ERC20 token from the local Truffle Develop instance and check the result.
    ${RESULT}=    Get Total Supply    %{CONTRACT_ADDRESS}
    Check Smart Contract Results And Log Them    ${RESULT}    totalSupply

TRUFFLE WEB3.JS TEST 7 : Get the estimated gas for a specific method from the deployed contract.
    ${RESULT}=    Get Gas Estimate    %{CONTRACT_ADDRESS}
    Check Smart Contract Results And Log Them    ${RESULT}    gasEstimation

TRUFFLE WEB3.JS TEST 8 : Get the current gas price in the local blockchain generated by Truffle Develop command.
    ${RESULT}=    Get Current Gas Price    %{CONTRACT_ADDRESS}
    Check Smart Contract Results And Log Them    ${RESULT}    gasPrice

*** Keywords ***

Check Smart Contract Results And Log Them
    [Arguments]    ${TRUFFLE_OUTPUT}    ${TRUFFLE_CHECK}
    Log    ${TRUFFLE_OUTPUT}
    Log To Console    ...
    Log To Console    ...
    Log To Console    ...
    Log To Console    ${TRUFFLE_OUTPUT}
    Log To Console    ...
    Log To Console    ...
    Log To Console    ...
    Should Not Be Empty    ${TRUFFLE_OUTPUT}
    Should Not Contain    ${TRUFFLE_OUTPUT}    Error
    Should Contain    ${TRUFFLE_OUTPUT}    ${TRUFFLE_CHECK}


