name: Robot Framework Solidity Testing Toolkit

title: Robot Framework Solidity Testing Toolkit
show_downloads: true
google_analytics:
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme