title: Robot Framework Solidity Testing Toolkit
github_username: jg8481 

# Build settings
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
