name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install all required Robot Framework dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt install python3.10
          python3 --version
          ls -la
          pip3 install -r ./requirements.txt
          robot -h
      - name: Install all required Hardhat dependencies
        run: |
          bash ./start-solidity-qa-workflows.sh Install-Tools-On-MacOS-Or-Linux
          node --version