name: Toolkit Checks
on:  
  push:
  pull_request:
  schedule:
      - cron: '0 0 * * 1'

jobs:

  run-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install all required Robot Framework dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 --version
          python3 -m venv venv
          source venv/bin/activate
          pip install -r ./solidity-hardhat-multichain-tools/requirements.txt
          pip freeze
          robot --nostatusrc --help | grep "Robot Framework is open source software"
          robot --nostatusrc --version | grep "Robot"
          echo "${GITHUB_WORKSPACE}/venv/bin" >> "$GITHUB_PATH"
      - name: Install NodeJS and all required Hardhat dependencies
        run: |
          bash ./start-solidity-qa-workflows.sh Install-Tools-On-MacOS-Or-Linux
          node --version
      - name: Run all unit tests using the BATS test framework
        run: |
          bash ./start-maintenance-workflows.sh Run-Unit-Tests

  run-acceptance-tests:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    timeout-minutes: 60    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install all required Robot Framework dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python3 --version
          python3 -m venv venv
          source venv/bin/activate
          pip install -r ./solidity-hardhat-multichain-tools/requirements.txt
          pip freeze
          robot --nostatusrc --help | grep "Robot Framework is open source software"
          robot --nostatusrc --version | grep "Robot"
          echo "${GITHUB_WORKSPACE}/venv/bin" >> "$GITHUB_PATH"
      - name: Install NodeJS and all required Hardhat dependencies
        run: |
          bash ./start-solidity-qa-workflows.sh Install-Tools-On-MacOS-Or-Linux
          node --version
      - name: Run all acceptance tests using the BATS test framework
        run: |
          bash ./start-maintenance-workflows.sh Run-Acceptance-Tests